### ISSUE TITLE
Documentation: dependency on 'check'

### ISSUE THREAD

**Issue by candlerb** [Yubico/libu2f-server#14]
At <https://developers.yubico.com/libu2f-server/> in the "Building" section it doesn't mention any dependencies. I already had the libu2f-host dependencies installed. But still got this error:

~~~
$ ./configure && make check
...
checking for CHECK... no
configure: error: Package requirements (check) were not met:

No package 'check' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
~~~

This is somewhat confusing. It turns out there is, in fact, a package called "check" which needs to be installed (`apt-get install check`).  This should probably be mentioned in the documentation

**Comment by a-dma** [comment]
Actually check has to be installed only if you also want to run tests with `make check`. I'll update the docs to make this clear.

**Comment by a-dma** [comment]
Actually there is already a note there saying

In order to perform self tests with make check, the Check Framework should be installed. However this is not required to build the library.
http://check.sourceforge.net/
Debian: apt-get install check

I think this is enough.

**Comment by candlerb** [comment]
Yes, sorry I didn't see that.
