### ISSUE TITLE
Test fails on Mac OS X

### ISSUE THREAD

**Issue by mouse07410** [Yubico/libu2f-server#18]
Mac OS X 10.11.6.

```
make[2]: Nothing to be done for `u2f-server-test.sh'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: basic
PASS: core
PASS: openssl
ERROR: u2f-server-test.sh
============================================================================
Testsuite summary for libu2f-server 1.0.2
============================================================================
# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 1
============================================================================
See tests/test-suite.log
Please report to yubico-devel@googlegroups.com
============================================================================
make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
$ 
```

`tests/test-suite.log`:

```
===============================================
   libu2f-server 1.0.2: tests/test-suite.log
===============================================

# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 1

.. contents:: :depth: 2

ERROR: u2f-server-test
======================

error: An origin must be specified with -o
Param = "register", result=1
error: An appId must be specified with -i
Param = "register", origin="http://yubico.com", result=1
u2f-server: unrecognized option `--unknown'
Param = "unknown", result=1
error: origin must be http, https or pam
Param = "unknown",origin="ftp://yubico.com", appid="http://yubico.com", result=1
error: (-2) Error in JSON handling
Param = "unknown",origin="http://yubico.com", appid="http://yubico.com", result=1
warning: challenge should be 43 characters long
error: (-2) Error in JSON handling
ERROR u2f-server-test.sh (exit status: 99)
```

**Comment by a-dma** [comment]
Relates to #3

**Comment by mouse07410** [comment]
> Relates to #3

I don't think I understand. What should be done to remedy the reported problem? Does a package need to be installed? If so - what package? Is it in any repo?

**Comment by mouse07410** [comment]
> Relates to #3

I don't think so:
```
$ sudo -H pip install webob
Password:
Requirement already satisfied (use --upgrade to upgrade): webob in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
$
```

@klali, this package doesn't even compile without this patch:
```
diff --git a/u2f-server/Makefile.am b/u2f-server/Makefile.am
index 9dac81b..984f72b 100644
--- a/u2f-server/Makefile.am
+++ b/u2f-server/Makefile.am
@@ -43,7 +43,7 @@ libu2f_server_la_SOURCES += cencode.c cdecode.c b64/cencode.h b64/cdecode.h
 libu2f_server_la_SOURCES += crypto.h
 libu2f_server_la_SOURCES += openssl.c
 
-libu2f_server_la_LIBADD = $(HIDAPI_LIBS) $(LIBJSON_LIBS) $(LIBSSL_LIBS)
+libu2f_server_la_LIBADD = $(HIDAPI_LIBS) $(LIBJSON_LIBS) $(LIBSSL_LIBS) $(LIBCRYPTO_LIBS)
 
 libu2f_server_la_LDFLAGS = -no-undefined \
        -version-info $(LT_CURRENT):$(LT_REVISION):$(LT_AGE)
```

**Comment by a-dma** [comment]
No, that was just a note saying that it relates to issue #3 (Port to Mac).
There hasn't been much testing on Mac, its version of PAM is a bit of a different beast. Weird that it doesn't even build. I'll try to have a look as soon as I can.

**Comment by mouse07410** [comment]
> Weird that it doesn't even build.

Maybe OpenSSL configuration (provided `*.pc` files) changed since this code was written?

> I'll try to have a look as soon as I can.

Thanks!

**Comment by mouse07410** [comment]
@a-dma...?

**Comment by a-dma** [comment]
Sorry, busy days as you might have understood.

I'll try to look into it next week

**Comment by a-dma** [comment]
I've had a quick look at this, it needs some work to get the project to build on macOS. Mostly I found that libjson is the first obstacle. It's not in homebrew and version 0.12 needs some tweaks to get it to build. As far as I can tell version 0.11 builds fine. Ideally we should have a dedicate Makefile like in [1].

[1] - https://github.com/Yubico/libu2f-host/blob/master/macosx.mk

**Comment by mouse07410** [comment]
> Mostly I found that libjson is the first obstacle. It's not in homebrew and version 0.12 needs some tweaks to get it to build. As far as I can tell version 0.11 builds fine.

I see, thank you for your efforts.  I have no problem building libjson 0.11 on my own, or 0.12. 

The concern is that several of Yubico U2F products appear to be dependent on it - and I'd rather not fix one to screw up something else. So perhaps a working libjson library build could be included?

Also, I don't use `homebrew` - only Macports, as between these two I found Macports to have fewer idiosyncrasies, and greater number of available packages (alas, libjson is not one of them :). And it is known that homebrew and Macports conflict when installed on the same machine.

**Comment by a-dma** [comment]
> The concern is that several of Yubico U2F products appear to be dependent on it - and I'd rather not fix one to screw up something else. So perhaps a working libjson library build could be included?
I think the library is fine, at least version 0.11 is. Finding libraries that not only work but are cross-platform and the right licensing is tricky sometimes. I think what this boils down to is having proper mac releases for libu2f-server and pam-u2f so that building them a more straightforward process.

**Comment by mouse07410** [comment]
Thanks for fixing this:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: basic
PASS: core
PASS: openssl
PASS: u2f-server-test.sh
============================================================================
Testsuite summary for libu2f-server 1.0.2
============================================================================
# TOTAL: 4
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
