### ISSUE TITLE
Generate random bytes less aggressively

### ISSUE THREAD

**Issue by frozencemetery** [Yubico/libu2f-server#34]
The `u2fs_init()` function unconditionally populates `challenge` with random bytes.  This is wasteful if the program is going to supply a challenge (`u2fs_set_challenge()`).

Also, nothing in the documentation for `u2fs_set_challenge()` or `u2fs_init()` suggests that this will be the case, which makes me suspect that many users are not aware of this behavior.

**Comment by a-dma** [comment]
True, the challenge could be generated inside `u2fs_registration_challenge` and `u2fs_authentication_challenge` if not present.

That being said, I don't see this as a big issue honestly. We can fix this when we're spending time on this project.
