### ISSUE TITLE
authenticate action fails with "open: No such file or directory"

### ISSUE THREAD

**Issue by dlo** [Yubico/libu2f-server#8]
The following command fails with a vague `open: No such file or directory`. Not sure what I'm doing wrong. It's possible I'm misusing the command, but the error message could be improved if so.

    u2f-server --origin pam://localhost --appid=pam://localhost -a authenticate --key-handle=/Users/dan/.config/Yubico/u2f_keys --user-key=dan --debug

**Comment by a-dma** [comment]
What's happening here is that the `--key-handle` parameter (and also the `--user-key`) specify where you want to write/read the key handle and the user key. More info at https://github.com/Yubico/libu2f-server#usage. In short, that has to be a file, not a directory, which is what I assume you are using in the example.

Agreed that the error message should be improved. I'll do that.
Thanks.

**Comment by dlo** [comment]
Got it. u2f_keys is a file, but "dan" was definitely not. I'll give it another go.
