### ISSUE TITLE
Add instructions for building from Git repo on OS X

### ISSUE THREAD

**Issue by dlo** [Yubico/libu2f-server#9]
What worked for me on OS X 10.11 (using Homebrew):

```
brew install hidapi gtk-doc gengetopt help2man check
git clone https://github.com/Yubico/libu2f-server
autoreconf --install
./configure
CFLAGS=-I$(brew --prefix openssl)/include make check
```

I also needed to append `--no-xmllint` after `$(A2X)` usage in the Makefile in order for the build to succeed.

Lastly, in order to move the pam module to /usr/lib/security on El Capitan, you need to remove the restrictions on sudo/root. See http://apple.stackexchange.com/a/202969/3186 for more information.

**Comment by a-dma** [comment]
I haven't tried building on 10.11 yet.
As I recall no extra steps were required to build on 10.10 but I know quite a few things have changed in the newer version.
I'll give it a try and incorporate yous instruction if they work for me as well.

Thanks.

**Comment by dlo** [comment]
Sounds good, let me know if you run into any issues! I'm writing up a Homebrew formula to keep it nice and reproducible.

**Comment by a-dma** [comment]
Nice, thanks. I'll give it a bash as soon as I can.
Also, worth keeping in mind that it is possible to copy the module in /usr/local/lib which is not protected by OS X's rootless nonsense.

**Comment by dlo** [comment]
Cool. Good point--hadn't thought of that.

BTW, here's the pull request I submitted to Homebrew with all the formula I threw together: https://github.com/Homebrew/homebrew/pull/43676

Note: pam_u2f builds from the Git repo--couldn't figure out how to build from archive.
